raw_data_path:
  '../data/raw/heart_cleveland_test.csv'
output_path:
  '../data/processed/heart_cleveland_test.csv'
target:
  'condition'
quantitative_features:
  - 'age'
  - 'trestbps'
  - 'chol'
  - 'thalach'
  - 'oldpeak'
  - 'ca'
categorical_features:
  - 'cp'
  - 'restecg'
  - 'slope'
  - 'thal'